languageCode = "en-us"
title = "Darija's art"
theme = "hugo-Portfolio"
defaultContentLanguage = "no"
baseurl = "/"

[languages]
    [languages.no]
        title = "Darija's Art"
        LanguageName = "Norsk"
        weight = 1
    [languages.en]
        title = "Darija's Art"
        LanguageName = "English"
        weight = 2
